#### Task 3: Import NumPy

This one is easy - just import the package 😄. Make sure to follow the conventions, though!

In [1]:
# Your code here
import numpy as np

#### Task 4: Python vs NumPy

Use pure Python and `numpy` to create a Python list/`numpy`:

- array of $10$ zeros;
- array of $10$ ones;
- array of $10$ fives;
- array of $10$ zeroes, the fifth value of which is $1$;
- array of all the integers from $10$ to $50$;
- array of all the even integers from $10$ to $50$;
- array that is the reversal of the list `[1, 2, 3]` (save these values in an object and use both methods to reverse that object);
- a 3x3 matrix with values ranging from $0$ to $8$;
- a 3x3 identity matrix;
- a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [18]:
# Your code here
print("Array of 10 zeros:")
p_zeros = [0 for _ in range(10)]
np_zeros = np.zeros(10)
print(f"Python: {p_zeros}")
print(f"Numpy: {np_zeros}\n")

print("Array of 10 ones:")
p_ones = [1 for _ in range(10)]
np_ones = np.ones(10)
print(f"Python: {p_ones}")
print(f"Numpy: {np_ones}\n")

print("Array of 10 fives:")
p_fives = [5 for _ in range(10)]
np_fives = np.full(10, 5)
print(f"Python: {p_fives}")
print(f"Numpy: {np_fives}\n")

print("Array of 10 zeroes, the fifth value of which is 1")
p_five_zeros = [0] * 10
p_five_zeros[4] = 1
np_five_zeros = np.zeros(10)
np_five_zeros[4] = 1
print(f"Python: {p_five_zeros}")
print(f"Numpy: {np_five_zeros}\n")

print("Array with all the integers from 10 to 50")
p_integers = [i for i in range(10, 51)]
np_integers = np.arange(10, 51)
print(f"Python: {p_integers}")
print(f"Numpy: {np_integers}\n")

print("Array with all the even integers from 10 to 50")
p_integers = [i for i in range(10, 51, 2)]
np_integers = np.arange(10, 51, 2)
print(f"Python: {p_integers}")
print(f"Numpy: {np_integers}\n")

print("Array that is the reversal of the list `[1, 2, 3]`")
p_l = [1, 2, 3]
np_l = np.array(p_l)
print(f"Python: {p_l[::-1]}")
print(f"Numpy: {np_l[::-1]}\n")

print("A 3x3 matrix with values ranging from 0 to 8")
p_matrix = [[i + j*3 for i in range(3)] for j in range(3)]
np_matrix = np.arange(9).reshape(3, 3)
print(f"Python: {p_matrix}")
print(f"Numpy: {np_matrix}\n")

print("A 3x3 identity matrix")
p_identity = [[1 if i == j else 0 for i in range(3)] for j in range(3)]
np_identity = np.identity(3)
print(f"Python: {p_identity}")
print(f"Numpy: {np_identity}\n")

print("A 5x5 matrix with values 1,2,3,4 just below the diagonal")
p_below_diag = [[i if i == j - 1 else 0 for i in range(5)] for j in range(5)]
np_below_diag = np.diag([1,2,3,4], k=-1)
print(f"Python: {p_below_diag}")
print(f"Numpy: {np_below_diag}\n")

Array of 10 zeros:
Python: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Numpy: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Array of 10 ones:
Python: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Numpy: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

Array of 10 fives:
Python: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
Numpy: [5 5 5 5 5 5 5 5 5 5]

Array of 10 zeroes, the fifth value of which is 1
Python: [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
Numpy: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Array with all the integers from 10 to 50
Python: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
Numpy: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

Array with all the even integers from 10 to 50
Python: [10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
Numpy: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]

Array that is the reversal

In [ ]:
# Expected result

array of 10 zeros
Python: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Numpy: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

array of 10 ones
Python: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Numpy: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

array of 10 fives
Python: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
Numpy: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]

array of 10 zeroes, the fifth value of which is 1
Python: [0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
Numpy: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

array of all the integers from 10 to 50
Python: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
Numpy: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]

array of all the even integers from 10 to 50
Python: [10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]
Numpy: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]

array that is the rever

#### Task 5: Using only NumPy:

1. Create a 5x5 array with $1$ on the border and $0$ inside.
2. Add a border filled with $0$'s on the two sides of an array `[1, 2, 3]`.
3. Create an array of $20$ equally spaced numbers between $0$ and $1$.
4. Create the following matrix:

```text
array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])
```

5. Find the indices of the non-zero elements in `[1, 2, 0, 0, 4, 0]`.

In [32]:
print("Create a 5x5 array with 1 on the border and 0 inside")
np_border = np.ones((5, 5))
np_border[1:-1, 1:-1] = 0
print(np_border, end="\n\n")

print("Add a border filled with '0s on the two sides of an array [1, 2, 3]")
np_list_border = np.array([1, 2, 3])
np_list_border = np.pad(np_list_border, 1, constant_values=0)
print(np_list_border, end="\n\n")

print("Create an array of 20 equally spaced numbers between 0 and 1")
np_equally_spaced = np.linspace(0, 1, 20)
print(np_equally_spaced, end="\n\n")

print("""Recreation of the matrix
[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
...
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]""")
np_matrix = np.arange(0.01, 1.01, 0.01).reshape(10, 10)
print(np_matrix)

print("Find the indices of the non-zero elements in [1, 2, 0, 0, 4, 0]")
np_array = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.where(np_array != 0)
# or non_zero_indices = np.nonzero(np_array)[0]
print(non_zero_indices[0], end="\n\n")

Create a 5x5 array with 1 on the border and 0 inside
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Add a border filled with '0s on the two sides of an array [1, 2, 3]
[0 1 2 3 0]

Create an array of 20 equally spaced numbers between 0 and 1
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]

Recreation of the matrix
[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
...
 [0.91 0.92 0.93 0.94 0.95 0.96 0.

In [ ]:
# Expected result

Create a 5x5 array with 1 on the border and 0 inside
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Add a border filled with '0s on the two sides of an array [1, 2, 3]
[0 1 2 3 0]

Create an array of 20 equally spaced numbers between 0 and 1
[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]

Recreation of the matrix
[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0

#### Task 6: Use NumPy to generate:

- a random number between 0 and 1;
- an array of 25 random numbers sampled from a standard normal distribution;
- a 3x3x3 array with random values drawn from the uniform distribution;
- a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values;
- a random array with values drawn from the uniform distribution of size 30 and find the mean value;
- and multiply a 5x3 matrix by a 3x2 matrix.

**Note**: Your values should be different from the one shown below due to randomness.

In [46]:
# Your code here
print("Generate a random number between 0 and 1")
np_random_num = np.random.random(1)
print(np_random_num[0], end="\n\n")

print(
    "an array of 25 random numbers sampled from a standard normal distribution"
)
np_25_random = np.random.randn(25)
print(np_25_random, end="\n\n")

print("a 3x3x3 array with random values drawn from the uniform distribution")
np_random_cube = np.random.rand(3, 3, 3)
print(np_random_cube, end="\n\n")

print(
    "a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values\nThe array:"
)
np_100_random = np.random.rand(10, 10)
print(np_100_random)
print(f"Minimum value: {np_100_random.min()}")
print(f"Maximum value: {np_100_random.max()}", end="\n\n")

print(
    "a random array with values drawn from the uniform distribution of size 30 and find the mean value\nThe array:"
)
np_30_random = np.random.rand(30)
print(np_30_random)
print("The mean value:", np_30_random.mean(), end="\n\n")

print("Multiply a 5x3 matrix by a 3x2 matrix")
np_matrix_a = np.random.rand(5, 3)
np_matrix_b = np.random.rand(3, 2)
print(f"Product of matrices a and b:\n{np_matrix_a @ np_matrix_b}\n") # like matmul

Generate a random number between 0 and 1
0.6813268667699087

an array of 25 random numbers sampled from a standard normal distribution
[-1.2098089  -0.34334676 -0.41175537 -1.17461629  1.13546594 -1.71140827
  1.41472331 -0.34697895  0.40192191  0.38046132  1.67986317 -0.65392255
 -0.14282877 -0.0109657   0.19699133  0.45437311  0.66820019  0.25391884
 -0.11417076 -0.6767109   0.0750262   0.76044326 -0.01170462  0.17833638
 -0.52352302]

a 3x3x3 array with random values drawn from the uniform distribution
[[[0.11826247 0.57751638 0.98683925]
  [0.28694375 0.4052617  0.50147945]
  [0.49605443 0.29752682 0.70879015]]

 [[0.04594038 0.4394121  0.25713228]
  [0.81061406 0.63274207 0.26292006]
  [0.28602884 0.81767778 0.62908456]]

 [[0.64716849 0.91944237 0.66350029]
  [0.60485739 0.94403887 0.77704998]
  [0.64831212 0.01731713 0.82042074]]]

a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values
The array:
[[0.59403021 0.27606776 0.300

In [ ]:
# Expected result

a random number between 0 and 1
0.3302392460734943

an array of 25 random numbers sampled from a standard normal distribution
[-0.85565418  0.4592446   0.90183199  0.53932203  0.04080838 -0.4210383
  1.00116207  0.08236895  0.08804113  0.11602095 -0.87912022  0.37818965
 -0.39515241  0.81614267 -0.73406941 -0.49574339 -0.4419727   2.66688758
  1.69571397  0.83054423  1.2732238  -1.55596546 -0.16924736 -1.12509893
 -0.05953329]

a 3x3x3 array with random values drawn from the uniform distribution
[[[0.42054451 0.27312439 0.95347927]
  [0.55134496 0.6235185  0.72550932]
  [0.37674019 0.56769456 0.58315167]]

 [[0.96651862 0.81392441 0.26927728]
  [0.758904   0.75618622 0.35625557]
  [0.12351087 0.43525117 0.68535189]]

 [[0.06672974 0.36402819 0.166292  ]
  [0.95530001 0.84750085 0.25077735]
  [0.95153091 0.8262242  0.86062338]]]

a 10x10 array with random values drawn from the uniform distribution and find the minimum and maximum values
The array:
[[0.32519229 0.66282593 0.61989954 0.07

#### Task 7: Write code that uses the below matrix to reproduce the expected output

In [47]:
# RUN THIS CELL - THIS IS OUR STARTING MATRIX
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
# Your code here
submatrix = mat[2:, 1:]
submatrix

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# Expected result

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [54]:
# Your code here
submatrix[1,3]

np.int64(20)

In [ ]:
# Expected result

np.int64(20)

In [65]:
# Your code here
# or (submatrix[:, 0] - 10).reshape(3, 1)
(submatrix[:, [0]] - 10)

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# Expected result

array([[ 2],
       [ 7],
       [12]])

In [66]:
# Your code here
mat[-1]

array([21, 22, 23, 24, 25])

In [ ]:
# Expected result

array([21, 22, 23, 24, 25])

In [69]:
# Your code here
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# Expected result

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Task 8: Continue using the matrix `mat` to calculate the:

- sum of its values;
- standard deviation of its values;
- the sum of all the columns;

In [70]:
# Your code here
mat.sum()

np.int64(325)

In [ ]:
# Expected result

np.int64(325)

In [71]:
# Your code here
mat.std()

np.float64(7.211102550927978)

In [ ]:
# Expected result

np.float64(7.211102550927978)

In [75]:
# Your code here
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])

In [ ]:
# Expected result

array([55, 60, 65, 70, 75])

#### Task 9: Let's practice composing operations:

1. Create a 1D array of random integers between $0$ and $9$. Negate all numbers that fall in the interval $[3, 8]$.
2. Create a random array with floating point values of size $10$ and sort it.
3. Create random vector of values drawn from the uniform distribution of size $10$ and replace the maximum value with $0$.

In [ ]:
# Your code here
np_09_random = np.random.randint(0, 10, 10)
np_09_random = np.where((np_09_random >= 3) & (np_09_random <= 8), -np_09_random, np_09_random)
np_09_random

array([ 9, -5,  2,  2, -3,  1, -7,  0, -5,  1], dtype=int32)

In [ ]:
# Expected result

array([-8,  0, -4, -8, -4,  2, -5, -5,  9, -7])

In [ ]:
# Your code here
np_10_floats = np.random.rand(10)
np_10_floats = np.sort(np_10_floats)
np_10_floats

array([0.05417675, 0.30380102, 0.3495271 , 0.35821196, 0.37334774,
       0.69156228, 0.69259575, 0.73682114, 0.82252693, 0.92191923])

In [ ]:
# Expected result

In [ ]:
np_max_replace = np.random.rand(10)
print(np_max_replace)
np_max_replace[np.argmax(np_max_replace)] = 0
np_max_replace

[0.41762455 0.83423937 0.33802537 0.90760261 0.68997532 0.96277808
 0.44346709 0.82346877 0.58079374 0.89396231]


array([0.41762455, 0.83423937, 0.33802537, 0.90760261, 0.68997532,
       0.        , 0.44346709, 0.82346877, 0.58079374, 0.89396231])

In [ ]:
# Expected result

The array: [0.44451769 0.53691507 0.76973933 0.64541201 0.78163228 0.49481479
 0.38390582 0.04337888 0.16149176 0.22652179]
Result: [0.44451769 0.53691507 0.76973933 0.64541201 0.         0.49481479
 0.38390582 0.04337888 0.16149176 0.22652179]


#### Task 10: Reproducibility

When training models, it's often important to generate the same random numbers every time the application is run, even if the machine changes. This ability helps us remove the possibility of creating the situation: *Well, it works on my machine...*.

Our code should work on all machines and produce the same results across different runs.

Go through the [documentation](https://numpy.org/doc/stable/reference/module_structure.html) and answer the below question.

How can we ensure that we always get the same random numbers (even if we switch machines)? Give two examples.

> **Your answer**:

First way is by using a random global seed applicable to all random generation.

It looks something like this np.random.seed(number)

There is a newer approach - we first set a random number generator

rng = np.random.default_rng(number)

and then using it like this

rng.random(...)

This approach is much better because we are not dealing with shared global state.
